# Generated by Django 3.1 on 2023-08-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ia_available',
            new_name='is_available',
        ),
    ]
