# Generated by Django 3.1 on 2023-08-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='upated_at',
            new_name='updated_at',
        ),
    ]
